### ISSUE TITLE
catch里面捕获不到异常？

### ISSUE THREAD

**Issue by carl0804** [John0King/uni-HttpClient#9]
如果正常返回数据是没问题的，但是如果获取数据不正确，在catch里没有打印信息
```
 "dependencies": {
    "uni-httpclient": "^1.4.1"
  },
```
使用hbuilder导入到js_sdk目录
```
import {httpClient, CancelToken, CancelError, StatusCodeError} from '../../js_sdk/join0king-httpclient/index.js'

                        getData() {		
				httpClient.get({
						url: 'https://jsonplaceholder.typicode.com/posts/asdf'  //地址不正确，模拟出错
					}).then(r => console.log(r))
					.catch(e => {
						if (e instanceof StatusCodeError) {
							this.result = `##返回代码错误：${e.statusCode}`
						} else if (e instanceof CancelError) {
							this.result = `##操作取消/超时了`
						} else {
							this.result = `## 出错了...${JSON.stringify(e)}`
						}
					})
			}

```

并没有打印出错信息，控制台输出：
```
GET https://jsonplaceholder.typicode.com/posts/asdf 404 ()
{} " at pages/mypage/mypage.vue:22"
```

**Comment by John0King** [comment]
@carl0804   请问是什么平台， web 么？  web的话需要 先支持 跨域 （但理论上可以被catch）
另外， 你有没有使用自己的拦截器，  拦截器里面 catch 以后一定要 throw 

-----------------------------------
我用那个 demo 试了下 (web 平台)
1. 没有 CORS 可以被 catch ， request fail  ， 这个原生的 Error
2. 配置了 CORS  也会拦截 , 得到 StatusCodeError , 而且会被demo里面的 全局错误拦截器拦截， 并且提示
![image](https://user-images.githubusercontent.com/13639146/125187267-4ad35100-e261-11eb-8eeb-7f509306edb6.png)
![image](https://user-images.githubusercontent.com/13639146/125187288-69394c80-e261-11eb-8527-4bb8696ba65f.png)

**Comment by John0King** [comment]
@carl0804   你的问题解决了么？ 没有的话， 能提供一个可以复现该问题的 demo么？

**Comment by carl0804** [comment]
> @carl0804 你的问题解决了么？ 没有的话， 能提供一个可以复现该问题的 demo么？

问题还没解决，我的运行平台是h5和微信小程序。

项目就是一个普通的uni-app项目。

```
<template>
	<view class="content">
		<view>
			<button @click="getDataFromServer">请求网络数据</button>
		</view>
	</view>
</template>

<script>
	import {
		httpClient,
		CancelToken,
		CancelError,
		StatusCodeError
	} from '@/js_sdk/join0king-httpclient/index.js'

	export default {
		data() {
			return {}
		},
		onLoad() {

		},
		methods: {
			getDataFromServer() {
				console.log('发送httpClient请求')
				// 正确url：https://jsonplaceholder.typicode.com/posts
					
				httpClient.get(`https://jsonplaceholder.typicode.com/posts/123`).then(r => console.log(r)).catch(e => {
					if (e instanceof StatusCodeError) {
						this.result = `##返回代码错误：${e.statusCode}`
					} else if (e instanceof CancelError) {
						this.result = `##操作取消/超时了`
					} else {
						this.result = `## 出错了...${JSON.stringify(e)}`
					}
				});
			}

		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}
</style>

```
<img width="234" alt="截屏2021-07-12 15 06 22" src="https://user-images.githubusercontent.com/25131086/125245187-d660e680-e322-11eb-8c4a-69a97540ca29.png">

**Comment by carl0804** [comment]
> @carl0804 你的问题解决了么？ 没有的话， 能提供一个可以复现该问题的 demo么？

开发环境：
Mac 10.15.7
HBuildx 3.1.22.20210709
测试使用的是内置浏览器和微信开发者工具
测试地址：https://jsonplaceholder.typicode.com/posts  #这是正确的url地址
https://jsonplaceholder.typicode.com/posts/123123123/ #这是错误的请求地址

ps：我使用uni-app时间很短，有限东西还不是很了解。如果是配置的问题，请多指教~

**Comment by John0King** [comment]
我的 demo 里面 this.result  是绑定到了页面上，  你的 页面上  data 里面没有  result 字段， 而且也没有把 result 输出， 我觉得你应该是想用  `console.log()` 输出到控制太吧 吧    或者你在 github上 给我提供的脚本是错的

**Comment by John0King** [comment]
@carl0804   刚创建了一个QQ群， 可以在里面聊，更方便   
QQ群： 665772319

**Comment by carl0804** [comment]
> 我的 demo 里面 this.result 是绑定到了页面上， 你的 页面上 data 里面没有 result 字段， 而且也没有把 result 输出， 我觉得你应该是想用 `console.log()` 输出到控制太吧 吧 或者你在 github上 给我提供的脚本是错的

不好意思，是想输出到控制台。
我再研究研究，可能是我的问题。

**Comment by John0King** [comment]
@carl0804   如果没有其他问题，我过会就关闭这个issue了，   如果你之后还遇到这个问题，  你可以 @我 , 让我重新打开这个issue， 被我关掉后， 你好像不能再reopen 的 样子。

**Comment by carl0804** [comment]
没问题了 谢谢！
